### ISSUE TITLE
More details on usage

### ISSUE THREAD

**Issue by dongli** [akshaykumar6/github-js#1]
Hi, @akshaykumar6 ,

`github-js` is very useful for me, but I don't know how to use it in my website. I am not familiar with JavaScript. Can you explain it more in the wiki pages? Thanks!

**Comment by akshaykumar6** [comment]
Hi @dongli,

Great, you found it useful. I got the same request from other guys also, I'll add `Getting started` guide soon.

**Comment by akshaykumar6** [comment]
@dongli I'm done with the [Getting Started Guide](https://github.com/akshaykumar6/github-js/wiki/Getting-Started). Let me know if it works for you.

**Comment by dongli** [comment]
@akshaykumar6 It works! I think you should emphasize that the `div` with id `myProfile` is needed. It cost me sometime to find it out. Sorry, I am not an expert of HTML and JavaScript~ :smile:
