### ISSUE TITLE
XSS bug

### ISSUE THREAD

**Issue by evverx** [akshaykumar6/github-js#4]
![screen shot 2015-04-15 at 11 18 02](https://cloud.githubusercontent.com/assets/10195800/7154689/2d5e206a-e361-11e4-875d-518ac6fadbb5.png)

**Comment by evverx** [comment]
Escape all the things:)
[`<%- … %>`](http://underscorejs.org/#template)

**Comment by akshaykumar6** [comment]
Thanks @evverx !! Can you send me the XSS string for testing?

**Comment by evverx** [comment]
`some-some`
[Github user](https://github.com/some-some) with `<img src="http://replygif.net/i/586.gif">` name

**Comment by akshaykumar6** [comment]
Thanks!
